--------------------------------------------------------------------------------
--
--      DO NOT EDIT - AUTOMATICALLY GENERATED BY SVT_APEX_SERT_UTIL.GENERATE_UNION_VIEW
--      Author:  HAYDEN.H.HUDSON@ORACLE.COM
-- Script name:  V_SVT_SERT__0.sql
--        Date:  23-Dec-2022 13:47
--     Purpose:  View creation DDL for view V_SVT_SERT__0
--
--------------------------------------------------------------------------------
create or replace force view v_SVT_sert__0 as
select as0.application_id, 
       as0.attribute_id, 
       as0.category_key, 
       as0.collection_name, 
       as0.component_signature, 
       as0.issue_title, 
       as0.LAST_updated_by, 
       as0.LAST_updated_on, 
       as0.link, 
       as0.link_desc, 
       as0.page_id, 
       as0.result, 
       as0.validation_failure_message,
       esst.standard_code
from v_eba_stds_standard_tests esst
join SVT_standard_view.v_SVT_sert__0(p_standard_code => esst.standard_code,p_failures_only => 'Y') as0
        on  esst.nt_name = 'V_SVT_SERT__0_NT'
        and esst.query_clob is not null
        and esst.active_yn = 'Y'
/