---
# ====== Application: Standard Violation Tracker =============
id: 17000033
identification: 
  name: Standard Violation Tracker
  alias: STANDARDS
  version: 2.2.1
  application-group: 20.1 Productivity Apps # 23752528892236742

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: svt_error_handler_api.error_handler

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: false
  allow-feedback: false
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1 / 22.2

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Application Express Accounts # 11984536357708947236

authorization: 
  authorization-scheme: MODEL.LOV.MUST_NOT_BE_PUBLIC_USER
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions
  maximum-session-length: 28800

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin-when-cross-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

advanced: 
  pass-ecid: N

database-session: 
  parsing-schema: AST

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: No NLS (Application not translated)
  automatic-time-zone: true
  automatic-csv-encoding: true

application-format-masks: 
  date: DD-MON-YYYY
  date-time: 'DD-MON-YYYY HH24:MI'

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: '&APP_NAME.'

progressive-web-app: 
  enable: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&SESSION.'
    page: 1 # V_SVT_PLSQL_APEX_AUDIT

navigation-menu: 
  list-template: Side Navigation Menu # 7573686090332144038
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation # 7103771714069154120

navigation-bar: 
  implementation: List
  list: Navigation Bar # 7586381283330477776
  list-template: Navigation Bar # 7573685941419144035
  template-options: 
  - '#DEFAULT#'

javascript: 
  file-urls: 
  - '#APP_IMAGES#js/svt.min.js'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#IMAGE_PREFIX#pkgapp_ui/css/5.0#MIN#.css'
  - '#APP_IMAGES#css/svtStyle.min.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: true
  add-"built-with-apex"-to-footer: true

substitutions: 
- # ====== Substitution: GETTING_STARTED_URL ===================
  id: 1
  identification: 
    name: GETTING_STARTED_URL

  value: 
    static-value: 'http://www.oracle.com/technetwork/developer-tools/apex/index.html'

- # ====== Substitution: APP_NAME ==============================
  id: 2
  identification: 
    name: APP_NAME

  value: 
    static-value: Standard Violation Tracker

- # ====== Substitution: APP_DATE_FORMAT =======================
  id: 3
  identification: 
    name: APP_DATE_FORMAT

  value: 
    static-value: DD-MON-YYYY

- # ====== Substitution: APP_DATE_TIME_FORMAT ==================
  id: 4
  identification: 
    name: APP_DATE_TIME_FORMAT

  value: 
    static-value: 'DD-MON-YYYY HH24:MI'

- # ====== Substitution: APP_EMAIL =============================
  id: 5
  identification: 
    name: APP_EMAIL

  value: 
    static-value: hayden.h.hudson@oracle.com

- # ====== Substitution: APP-NAME-TITLE ========================
  id: 6
  identification: 
    name: APP-NAME-TITLE

  value: 
    static-value: '[SVT]'

