---
# ====== Application: Standard Violation Tracker =============
id: 17000033
identification: 
  name: Standard Violation Tracker
  alias: SVT
  version: 3.0
  application-group: 20.1 Productivity Apps # 29207252472220767

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: svt_error_handler_api.error_handler

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: false
  allow-feedback: false
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1 / 22.2
  pass-ecid: N

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Application Express Accounts # 12233309588292284697

authorization: 
  authorization-scheme: MODEL.LOV.MUST_NOT_BE_PUBLIC_USER
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions
  maximum-session-length: 28800

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin-when-cross-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: ACCESSIBILITY

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: No NLS (Application not translated)
  automatic-time-zone: true
  automatic-csv-encoding: true

application-format-masks: 
  date: DD-MON-YYYY
  date-time: 'DD-MON-YYYY HH24:MI'

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: '&APP_NAME.'

progressive-web-app: 
  enable: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&SESSION.'
    page: 1 # Issue Tracking

navigation-menu: 
  list-template: Top Navigation Menu # 7822458590678481494
  template-options: 
  - '#DEFAULT#'
  - js-tabLike
  list-position: Top

navigation-bar: 
  implementation: List
  list: Navigation # 7352544944652491581
  list-template: Navigation Bar # 7822459172002481496
  template-options: 
  - '#DEFAULT#'

javascript: 
  file-urls: 
  - '#APP_IMAGES#js/svt.min.js'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#IMAGE_PREFIX#pkgapp_ui/css/5.0#MIN#.css'
  - '#APP_IMAGES#css/svtStyle.min.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: true
  add-"built-with-apex"-to-footer: true

substitutions: 
- # ====== Substitution: GETTING_STARTED_URL ===================
  id: 1
  identification: 
    name: GETTING_STARTED_URL

  value: 
    static-value: 'http://www.oracle.com/technetwork/developer-tools/apex/index.html'

- # ====== Substitution: APP_NAME ==============================
  id: 2
  identification: 
    name: APP_NAME

  value: 
    static-value: '&A_APP_NAME.'

- # ====== Substitution: APP_DATE_FORMAT =======================
  id: 3
  identification: 
    name: APP_DATE_FORMAT

  value: 
    static-value: DD-MON-YYYY

- # ====== Substitution: APP_DATE_TIME_FORMAT ==================
  id: 4
  identification: 
    name: APP_DATE_TIME_FORMAT

  value: 
    static-value: 'DD-MON-YYYY HH24:MI'

- # ====== Substitution: APP_EMAIL =============================
  id: 5
  identification: 
    name: APP_EMAIL

  value: 
    static-value: hayden.h.hudson@oracle.com

- # ====== Substitution: APP-NAME-TITLE ========================
  id: 6
  identification: 
    name: APP-NAME-TITLE

  value: 
    static-value: '[SVT]'

component-settings: 
- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 7278759285662501
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 37166586778912

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 559608890946228209
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  settings: 
    attribute-1: Y

  subscription: 
    version-number: 37166586778912

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 560328517730244184
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 37166586778912

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 564909579757967028
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 37166586778912

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 564909719075967028
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 37166586778912

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 6395339643660628298
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 37166586778912

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 8161491838935510420
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  settings: 
    attribute-1: N

  subscription: 
    version-number: 37166586778912

- # ====== Component Setting: NATIVE_IR ========================
  id: 8228192104831792517
  identification: 
    name: NATIVE_IR
    type: Region

  settings: 
    attribute-1: IG

  subscription: 
    version-number: 37166586778912

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 8314081439999738435
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 37166586778912

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 8977476827574214166
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH

  subscription: 
    version-number: 37166586778912

