--liquibase formatted sql
--changeset table_script:AHA_TEAMS stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('AHA_TEAMS');

create table aha_teams (
    id                             number generated by default on null as identity 
                                   constraint aha_teams_id_pk primary key,
    name                           varchar2(255 char)
)
;

create table aha_developers (
    id                             number generated by default on null as identity 
                                   constraint aha_developers_id_pk primary key,
    aha_team_id                    number
                                   constraint aha_developers_aha_team_id_fk
                                   references aha_teams,
    email                          varchar2(255 char)
)
;

create table aha_team_app_types (
    id                             number generated by default on null as identity 
                                   constraint aha_team_app_types_id_pk primary key,
    aha_team_id                    number
                                   constraint aha_team_app_ty_aha_team_id_fk
                                   references aha_teams,
    app_type_id                    number
                                   constraint aha_team_app_ty_app_type_id_fk
                                   references eba_stds_types
)
;

-- table index
create index aha_developers_i1 on aha_developers (aha_team_id);
create index aha_team_app_types_i1 on aha_team_app_types (aha_team_id);
create index aha_team_app_types_i82 on aha_team_app_types (app_type_id);

--rollback drop table AHA_TEAMS;
