--liquibase formatted sql
--changeset table_script:AST_AUDIT_ACTIONS stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('AST_AUDIT_ACTIONS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  AST_AUDIT_ACTIONS.sql
--        Date:  10-Apr-2023 19:39
--     Purpose:  Table creation DDL for table AST_AUDIT_ACTIONS
--               and related objects.
--
--------------------------------------------------------------------------------


  CREATE TABLE AST_AUDIT_ACTIONS 
   (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	ACTION_NAME VARCHAR2(255 CHAR), 
  INCLUDE_IN_REPORT_YN VARCHAR2(1),
	CREATED DATE, 
	CREATED_BY VARCHAR2(255 CHAR), 
	UPDATED DATE, 
	UPDATED_BY VARCHAR2(255 CHAR)
   ) 
/




  ALTER TABLE AST_AUDIT_ACTIONS MODIFY (UPDATED_BY NOT NULL ENABLE)
/


  ALTER TABLE AST_AUDIT_ACTIONS MODIFY (CREATED NOT NULL ENABLE)
/


  ALTER TABLE AST_AUDIT_ACTIONS MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE AST_AUDIT_ACTIONS MODIFY (UPDATED NOT NULL ENABLE)
/

--precondition-sql-check expectedResult:0 select count(*) from user_constraints where upper(constraint_name)  = 'AST_ADTACT_PK'

  ALTER TABLE AST_AUDIT_ACTIONS ADD CONSTRAINT AST_ADTACT_PK PRIMARY KEY (ID)
  USING INDEX (CREATE UNIQUE INDEX AST_ADTACT_PK_IDX ON AST_AUDIT_ACTIONS (ID) 
  )  ENABLE
/


--rollback drop table AST_AUDIT_ACTIONS;

--changeset table_script:AST_AUDIT_ACTIONS.include_in_report_yn stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tab_cols where upper(table_name) = 'AST_AUDIT_ACTIONS' and upper(column_name) = 'INCLUDE_IN_REPORT_YN';
alter table ast_audit_actions add (include_in_report_yn varchar2(1) default 'Y')
/

--rollback alter table ast_audit_actions drop column include_in_report_yn;