--liquibase formatted sql
--changeset table_script:EBA_STDS_USERS stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('EBA_STDS_USERS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  EBA_STDS_USERS.sql
--        Date:  04-Apr-2023 21:45
--     Purpose:  Table creation DDL for table EBA_STDS_USERS
--               and related objects.
--
--------------------------------------------------------------------------------

  CREATE TABLE EBA_STDS_USERS 
   (	ID NUMBER, 
      USERNAME VARCHAR2(255), 
      ACCESS_LEVEL_ID NUMBER, 
      ACCOUNT_LOCKED VARCHAR2(1), 
      ROW_VERSION_NUMBER NUMBER, 
      CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      CREATED_BY VARCHAR2(255), 
      UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      UPDATED_BY VARCHAR2(255)
   ) 
/

  CREATE INDEX EBA_STDUSR_IDX1 ON EBA_STDS_USERS (ACCESS_LEVEL_ID) 
  
/


  ALTER TABLE EBA_STDS_USERS MODIFY (USERNAME NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_USERS MODIFY (ACCESS_LEVEL_ID NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_USERS MODIFY (ACCOUNT_LOCKED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_USERS MODIFY (ROW_VERSION_NUMBER NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_USERS MODIFY (CREATED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_USERS MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_USERS MODIFY (UPDATED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_USERS MODIFY (UPDATED_BY NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_USERS ADD CONSTRAINT EBA_STDUSR_CK1 CHECK (account_locked in ('Y','N')) ENABLE
/


  ALTER TABLE EBA_STDS_USERS ADD CONSTRAINT EBA_STDUSR_PK PRIMARY KEY (ID)
  USING INDEX (CREATE UNIQUE INDEX EBA_STDUSR_PK_IDX ON EBA_STDS_USERS (ID) 
  )  ENABLE
/


  ALTER TABLE EBA_STDS_USERS ADD CONSTRAINT EBA_STDUSR_UK1 UNIQUE (USERNAME)
  USING INDEX (CREATE UNIQUE INDEX EBA_STDUSR_UK1_IDX ON EBA_STDS_USERS (USERNAME) 
  )  ENABLE
/


--rollback drop table EBA_STDS_USERS;
