--liquibase formatted sql
--changeset table_script:eba_stds_inherited_tests stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('eba_stds_inherited_tests');

CREATE TABLE EBA_STDS_INHERITED_TESTS (
    ID                             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
                                   CONSTRAINT EBA_STDS_INHERITED_ID_PK PRIMARY KEY,
    PARENT_STANDARD_ID             NUMBER NOT NULL,
    TEST_ID                        NUMBER NOT NULL,
    STANDARD_ID                    NUMBER NOT NULL,
    CREATED                        DATE NOT NULL,
    CREATED_BY                     VARCHAR2(255 CHAR) NOT NULL,
    UPDATED                        DATE NOT NULL,
    UPDATED_BY                     VARCHAR2(255 CHAR) NOT NULL
)
/

alter table eba_stds_inherited_tests
add constraint eb_std_inh_c1 check (parent_standard_id != standard_id);
/

  alter table eba_stds_inherited_tests add constraint eb_std_inh_uk1 unique (standard_id, test_id)
  using index  enable
/

create index eb_std_inh_idx1 on eba_stds_inherited_tests (parent_standard_id,test_id)
/
 
--rollback drop table eba_stds_inherited_tests;
