--liquibase formatted sql
--changeset table_script:EBA_STDS_PREFERENCES stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('EBA_STDS_PREFERENCES');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  EBA_STDS_PREFERENCES.sql
--        Date:  04-Apr-2023 21:38
--     Purpose:  Table creation DDL for table EBA_STDS_PREFERENCES
--               and related objects.
--
--------------------------------------------------------------------------------

  CREATE TABLE EBA_STDS_PREFERENCES 
   (	ID NUMBER, 
      PREFERENCE_NAME VARCHAR2(255 CHAR),
      PREFERENCE_VALUE VARCHAR2(255 CHAR),
      ROW_VERSION_NUMBER NUMBER, 
      CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      CREATED_BY VARCHAR2(255 CHAR),
      UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      UPDATED_BY VARCHAR2(255 CHAR)
   ) 
/


  ALTER TABLE EBA_STDS_PREFERENCES MODIFY (PREFERENCE_NAME NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_PREFERENCES MODIFY (PREFERENCE_VALUE NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_PREFERENCES MODIFY (ROW_VERSION_NUMBER NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_PREFERENCES MODIFY (CREATED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_PREFERENCES MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_PREFERENCES MODIFY (UPDATED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_PREFERENCES MODIFY (UPDATED_BY NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_PREFERENCES ADD CONSTRAINT EBA_STDPRF_PK PRIMARY KEY (ID)
  USING INDEX (CREATE UNIQUE INDEX EBA_STDPRF_PK_IDX ON EBA_STDS_PREFERENCES (ID) 
  )  ENABLE
/


  ALTER TABLE EBA_STDS_PREFERENCES ADD CONSTRAINT EBA_STDPRF_UK1 UNIQUE (PREFERENCE_NAME)
  USING INDEX (CREATE UNIQUE INDEX EBA_STDPRF_UK1_IDX ON EBA_STDS_PREFERENCES (PREFERENCE_NAME) 
  )  ENABLE
/


--rollback drop table EBA_STDS_PREFERENCES;
