--liquibase formatted sql
--changeset table_script:EBA_STDS_NOTIFICATIONS stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('EBA_STDS_NOTIFICATIONS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  EBA_STDS_NOTIFICATIONS.sql
--        Date:  04-Apr-2023 21:36
--     Purpose:  Table creation DDL for table EBA_STDS_NOTIFICATIONS
--               and related objects.
--
--------------------------------------------------------------------------------

  CREATE TABLE EBA_STDS_NOTIFICATIONS 
   (	ID NUMBER, 
      NOTIFICATION_NAME VARCHAR2(255 CHAR),
      NOTIFICATION_DESCRIPTION VARCHAR2(4000 CHAR),
      NOTIFICATION_TYPE VARCHAR2(30 CHAR),
      DISPLAY_SEQUENCE NUMBER, 
      DISPLAY_FROM TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      DISPLAY_UNTIL TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      ROW_VERSION_NUMBER NUMBER, 
      CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      CREATED_BY VARCHAR2(255 CHAR),
      UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      UPDATED_BY VARCHAR2(255 CHAR)
   ) 
/

  ALTER TABLE EBA_STDS_NOTIFICATIONS MODIFY (NOTIFICATION_NAME NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_NOTIFICATIONS MODIFY (NOTIFICATION_TYPE NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_NOTIFICATIONS MODIFY (ROW_VERSION_NUMBER NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_NOTIFICATIONS MODIFY (CREATED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_NOTIFICATIONS MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_NOTIFICATIONS MODIFY (UPDATED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_NOTIFICATIONS MODIFY (UPDATED_BY NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_NOTIFICATIONS ADD CONSTRAINT EBA_STDNTF_CK1 CHECK (notification_type in ('RED','YELLOW')) ENABLE
/


  ALTER TABLE EBA_STDS_NOTIFICATIONS ADD CONSTRAINT EBA_STDNTF_PK PRIMARY KEY (ID)
  USING INDEX (CREATE UNIQUE INDEX EBA_STDNTF_PK_IDX ON EBA_STDS_NOTIFICATIONS (ID) 
  )  ENABLE
/


  ALTER TABLE EBA_STDS_NOTIFICATIONS ADD CONSTRAINT EBA_STDNTF_UK1 UNIQUE (NOTIFICATION_NAME)
  USING INDEX (CREATE UNIQUE INDEX EBA_STDNTF_UK1_IDX ON EBA_STDS_NOTIFICATIONS (NOTIFICATION_NAME) 
  )  ENABLE
/


--rollback drop table EBA_STDS_NOTIFICATIONS;
