--liquibase formatted sql
--changeset table_script:EBA_STDS_TZ_PREF stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('EBA_STDS_TZ_PREF');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  EBA_STDS_TZ_PREF.sql
--        Date:  04-Apr-2023 22:14
--     Purpose:  Table creation DDL for table EBA_STDS_TZ_PREF
--               and related objects.
--
--------------------------------------------------------------------------------

  CREATE TABLE EBA_STDS_TZ_PREF 
   (	ID NUMBER, 
	USERNAME VARCHAR2(255), 
	TIMEZONE_PREFERENCE VARCHAR2(255), 
	ROW_VERSION_NUMBER NUMBER, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255)
   ) 
/


  ALTER TABLE EBA_STDS_TZ_PREF MODIFY (USERNAME NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_TZ_PREF MODIFY (TIMEZONE_PREFERENCE NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_TZ_PREF MODIFY (ROW_VERSION_NUMBER NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_TZ_PREF MODIFY (CREATED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_TZ_PREF MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_TZ_PREF MODIFY (UPDATED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_TZ_PREF MODIFY (UPDATED_BY NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_TZ_PREF ADD CONSTRAINT EBA_STTZPR_PK PRIMARY KEY (ID)
  USING INDEX (CREATE UNIQUE INDEX EBA_STTZPR_PK_IDX ON EBA_STDS_TZ_PREF (ID) 
  )  ENABLE
/


  ALTER TABLE EBA_STDS_TZ_PREF ADD CONSTRAINT EBA_STTZPR_UK1 UNIQUE (USERNAME)
  USING INDEX (CREATE UNIQUE INDEX EBA_STTZPR_UK1_IDX ON EBA_STDS_TZ_PREF (USERNAME) 
  )  ENABLE
/


--rollback drop table EBA_STDS_TZ_PREF;
