--liquibase formatted sql
--changeset table_script:EBA_STDS_STANDARD_TESTS stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('EBA_STDS_STANDARD_TESTS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  EBA_STDS_STANDARD_TESTS.sql
--        Date:  10-Apr-2023 17:45
--     Purpose:  Table creation DDL for table EBA_STDS_STANDARD_TESTS
--               and related objects.
-- data is deployed via EBA_STDS_TESTS_LIB
--
--------------------------------------------------------------------------------


  CREATE TABLE EBA_STDS_STANDARD_TESTS 
   (	ID NUMBER, 
      STANDARD_ID NUMBER, 
      TEST_NAME VARCHAR2(64), 
      DISPLAY_SEQUENCE NUMBER, 
      QUERY_CLOB CLOB, 
      OWNER VARCHAR2(128) DEFAULT sys_context('userenv','current_schema'), 
      TEST_CODE VARCHAR2(100), 
      LEVEL_ID NUMBER,
      EXPLANATION VARCHAR2(4000 CHAR), 
      FIX CLOB,
      ACTIVE_YN VARCHAR2(1) DEFAULT 'Y', 
      VERSION_NUMBER NUMBER,
      MV_DEPENDENCY VARCHAR2(100),
      SVT_COMPONENT_TYPE_ID NUMBER,
      CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      CREATED_BY VARCHAR2(255), 
      UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      UPDATED_BY VARCHAR2(255)
   ) 
/

  CREATE INDEX EBA_STSTTS_IDX1 ON EBA_STDS_STANDARD_TESTS (STANDARD_ID) 
/
  CREATE INDEX EBA_STSTTS_IDX4 ON EBA_STDS_STANDARD_TESTS (LEVEL_ID) 
/
  ALTER TABLE EBA_STDS_STANDARD_TESTS MODIFY (TEST_CODE NOT NULL ENABLE)
/
  ALTER TABLE EBA_STDS_STANDARD_TESTS MODIFY (STANDARD_ID NOT NULL ENABLE)
/
  ALTER TABLE EBA_STDS_STANDARD_TESTS MODIFY (TEST_NAME NOT NULL ENABLE)
/
  ALTER TABLE EBA_STDS_STANDARD_TESTS MODIFY (CREATED NOT NULL ENABLE)
/
  ALTER TABLE EBA_STDS_STANDARD_TESTS MODIFY (CREATED_BY NOT NULL ENABLE)
/
  ALTER TABLE EBA_STDS_STANDARD_TESTS MODIFY (UPDATED NOT NULL ENABLE)
/
  ALTER TABLE EBA_STDS_STANDARD_TESTS MODIFY (UPDATED_BY NOT NULL ENABLE)
/
  ALTER TABLE EBA_STDS_STANDARD_TESTS ADD CONSTRAINT EBA_STDS_STANDARD_TESTS_UK1 UNIQUE (test_name)
  USING INDEX  ENABLE
/
  ALTER TABLE EBA_STDS_STANDARD_TESTS ADD CONSTRAINT EBA_STSTTS_PK PRIMARY KEY (ID)
  USING INDEX (CREATE UNIQUE INDEX EBA_STSTTS_PK_IDX ON EBA_STDS_STANDARD_TESTS (ID) 
  )  ENABLE
/

ALTER TABLE EBA_STDS_STANDARD_TESTS MODIFY (SVT_COMPONENT_TYPE_ID NOT NULL ENABLE)
/

ALTER TABLE EBA_STDS_STANDARD_TESTS ADD CONSTRAINT EBA_STDS_STANDARD_TESTS_UK2 UNIQUE (test_code)
USING INDEX  ENABLE
/

  ALTER TABLE EBA_STDS_STANDARD_TESTS MODIFY (VERSION_NUMBER NOT NULL ENABLE)
/

  ALTER TABLE EBA_STDS_STANDARD_TESTS ADD CONSTRAINT EBA_STDS_STANDARD_TESTS_UK3 UNIQUE (standard_id, id)
  USING INDEX  ENABLE
/
-- constraint eba_ststts_ast_cmpnt_tp_fk1 on column(s) svt_component_type_id is missing an index
create index eba_stds_standard_tests_idx1 on eba_stds_standard_tests (svt_component_type_id)
/

--rollback drop table EBA_STDS_STANDARD_TESTS;