--liquibase formatted sql
--changeset table_script:EBA_STDS_APPLICATIONS stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('EBA_STDS_APPLICATIONS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  EBA_STDS_APPLICATIONS.sql
--        Date:  10-Apr-2023 19:41
--     Purpose:  Table creation DDL for table EBA_STDS_APPLICATIONS
--               and related objects.
--
/*
Initialize this table with the a2_initial_data_load script
*/
--------------------------------------------------------------------------------

  create table eba_stds_applications 
   (	pk_id             number generated by default on null as identity,
      apex_app_id       number not null, 
      default_developer varchar2(100 char),
      type_id           number,
      notes             varchar2(4000 char),
      active_yn         varchar2(1 char) default 'Y',
      esa_created       timestamp (6) with local time zone default systimestamp not null, 
      esa_created_by    varchar2(255 char)                 default user not null, 
      esa_updated       timestamp (6) with local time zone default systimestamp not null, 
      esa_updated_by    varchar2(255 char)                 default user not null
   ) 
/

--precondition-sql-check expectedResult:0 select count(*) from user_constraints where upper(constraint_name)  = 'EBA_STDS_APPLICATIONS_PK'

  alter table eba_stds_applications add constraint eba_stds_applications_pk primary key (pk_id)
  using index  enable
/

--precondition-sql-check expectedResult:0 select count(*) from user_constraints where upper(constraint_name)  = 'EBA_STDAPP_UK1'

  alter table eba_stds_applications add constraint eba_stdapp_uk1 unique (apex_app_id)
  using index (create unique index eba_stdapp_uk1_idx on eba_stds_applications (apex_app_id) 
  )  enable
/

create index eba_stdapp_idx1 on eba_stds_applications (type_id)
/

--rollback drop table EBA_STDS_APPLICATIONS;
