--liquibase formatted sql
--changeset table_script:EBA_TEST_HELP_LIB stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('EBA_TEST_HELP_LIB');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  EBA_TEST_HELP_LIB.sql
--        Date:  08-Jun-2023 21:55
--     Purpose:  Table creation DDL for table EBA_TEST_HELP_LIB
--               and related objects.
-- preserved contents of AST_SUB_REFERENCE_CODES for deployment
--
--------------------------------------------------------------------------------

-- drop table EBA_TEST_HELP_LIB
-- /
  CREATE TABLE EBA_TEST_HELP_LIB 
   (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE, 
	    WORKSPACE VARCHAR2(225), 
	    TEST_ID NUMBER,
	    STANDARD_CODE VARCHAR2(100), 
      SUB_CODE VARCHAR2(100) DEFAULT 'NA', 
      EXPLANATION VARCHAR2(4000 CHAR), 
      FIX CLOB
   ) 
/


  ALTER TABLE EBA_TEST_HELP_LIB MODIFY (STANDARD_CODE NOT NULL ENABLE)
/


  ALTER TABLE EBA_TEST_HELP_LIB MODIFY (WORKSPACE NOT NULL ENABLE)
/

--precondition-sql-check expectedResult:0 select count(*) from user_constraints where upper(constraint_name)  = 'EBA_TSHLP_LIB_PK'

  ALTER TABLE EBA_TEST_HELP_LIB ADD CONSTRAINT EBA_TSHLP_LIB_PK PRIMARY KEY (ID)
  USING INDEX (CREATE UNIQUE INDEX EBA_TSHLP_LIB_IDX ON EBA_TEST_HELP_LIB (ID) 
  )  ENABLE
/

--precondition-sql-check expectedResult:0 select count(*) from user_constraints where upper(constraint_name)  = 'EBA_TSHLP_LIB_UK1'

  ALTER TABLE EBA_TEST_HELP_LIB ADD CONSTRAINT EBA_TSHLP_LIB_UK1 UNIQUE (WORKSPACE, SUB_CODE)
  USING INDEX  ENABLE
/


--rollback drop table EBA_TEST_HELP_LIB;
