--liquibase formatted sql
--changeset table_script:EBA_STDS_STANDARDS stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('EBA_STDS_STANDARDS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  EBA_STDS_STANDARDS.sql
--        Date:  07-Apr-2023 22:36
--     Purpose:  Table creation DDL for table EBA_STDS_STANDARDS
--               and related objects.
--
--------------------------------------------------------------------------------


  CREATE TABLE EBA_STDS_STANDARDS 
   (	ID NUMBER, 
      STANDARD_NAME VARCHAR2(64), 
      DESCRIPTION VARCHAR2(4000), 
      PRIMARY_DEVELOPER VARCHAR2(255), 
      IMPLEMENTATION CLOB, 
      DATE_STARTED TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT localtimestamp, 
      CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      CREATED_BY VARCHAR2(255), 
      UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
      UPDATED_BY VARCHAR2(255), 
      STANDARD_GROUP VARCHAR2(32),
      ACTIVE_YN VARCHAR2(1)
   ) 
/


  ALTER TABLE EBA_STDS_STANDARDS MODIFY (STANDARD_NAME NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_STANDARDS MODIFY (DATE_STARTED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_STANDARDS MODIFY (CREATED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_STANDARDS MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_STANDARDS MODIFY (UPDATED NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_STANDARDS MODIFY (UPDATED_BY NOT NULL ENABLE)
/


  ALTER TABLE EBA_STDS_STANDARDS ADD CONSTRAINT EBA_STDSTN_PK PRIMARY KEY (ID)
  USING INDEX (CREATE UNIQUE INDEX EBA_STDSTN_PK_IDX ON EBA_STDS_STANDARDS (ID) 
  )  ENABLE
/

 ALTER TABLE EBA_STDS_STANDARDS add (ACTIVE_YN VARCHAR2(1))
/

  ALTER TABLE EBA_STDS_STANDARDS MODIFY (ACTIVE_YN NOT NULL ENABLE)
/

--rollback drop table EBA_STDS_STANDARDS;