--liquibase formatted sql
--changeset table_script:SVT_AUDIT_ACTIONS stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_AUDIT_ACTIONS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  SVT_AUDIT_ACTIONS.sql
--        Date:  10-Apr-2023 19:39
--     Purpose:  Table creation DDL for table SVT_AUDIT_ACTIONS
--               and related objects.
--
--------------------------------------------------------------------------------


  CREATE TABLE SVT_AUDIT_ACTIONS 
   (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      ACTION_NAME VARCHAR2(255 CHAR), 
      -- INCLUDE_IN_REPORT_YN VARCHAR2(1) DEFAULT 'Y',
      INCLUDE_IN_REPORT_YN VARCHAR2(1),
      CREATED DATE, 
      CREATED_BY VARCHAR2(255 CHAR), 
      UPDATED DATE, 
      UPDATED_BY VARCHAR2(255 CHAR)
   ) 
/

  ALTER TABLE SVT_AUDIT_ACTIONS MODIFY (UPDATED_BY NOT NULL ENABLE)
/


  ALTER TABLE SVT_AUDIT_ACTIONS MODIFY (CREATED NOT NULL ENABLE)
/


  ALTER TABLE SVT_AUDIT_ACTIONS MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE SVT_AUDIT_ACTIONS MODIFY (UPDATED NOT NULL ENABLE)
/

  ALTER TABLE SVT_AUDIT_ACTIONS MODIFY (INCLUDE_IN_REPORT_YN NOT NULL ENABLE)
/

--precondition-sql-check expectedResult:0 select count(*) from user_constraints where upper(constraint_name)  = 'SVT_ADTACT_PK'

  ALTER TABLE SVT_AUDIT_ACTIONS ADD CONSTRAINT SVT_ADTACT_PK PRIMARY KEY (ID)
  USING INDEX (CREATE UNIQUE INDEX SVT_ADTACT_PK_IDX ON SVT_AUDIT_ACTIONS (ID) 
  )  ENABLE
/

--rollback drop table SVT_AUDIT_ACTIONS;