--liquibase formatted sql
--changeset table_script:SVT_COMPONENT_TYPES stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_COMPONENT_TYPES');
------------------------------------------------------------------------------
--  Creator: Hayden Hudson
--     Date: May 25, 2023
-- Synopsis:
--
-- This table is designed to house the components from WWV_FLOW_DICTIONARY_VIEWS,
-- to which I am linking from my tests
--
------------------------------------------------------------------------------
create table SVT_COMPONENT_TYPES (
  ID GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE,
  component_name    varchar2(50) not null, --WWV_FLOW_DICTIONARY_VIEWS.view_name
  component_code    varchar2(40), -- a way to bridge the gap from previous method
  available_yn      varchar2(1) not null,
  nt_type_id        number, 
  pk_value          varchar2(50),
  parent_pk_value   varchar2(50),
  template_url      varchar2(250),
  friendly_name     varchar2(50),
  name_column       varchar2(100),
  addl_cols         varchar2(1000),
  created           date not null,
	created_by        varchar2(255 char) not null,
	updated           date not null,
	updated_by        varchar2(255 char) not null
)
/
ALTER TABLE svt_component_types ADD CONSTRAINT uk_componentname UNIQUE(component_name);
/
ALTER TABLE svt_component_types ADD CONSTRAINT svt_component_types_pk PRIMARY KEY (id);
/
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where upper(constraint_name) = 'EBA_STSTTS_EBA_STDSTN_FK2';

 
--rollback drop table SVT_COMPONENT_TYPES;
  
  CREATE INDEX SVT_COMPONENT_TYPES_IDX1 ON SVT_COMPONENT_TYPES (NT_TYPE_ID) 
  
 ALTER TABLE SVT_COMPONENT_TYPES MODIFY (NT_TYPE_ID NOT NULL ENABLE)
/
ALTER TABLE svt_component_types
ADD CONSTRAINT componentname_uk2 UNIQUE(column_name1, column_nam2)
/

--precondition-sql-check expectedResult:0 select count(1) from all_tab_cols where table_name = 'SVT_COMPONENT_TYPES' and column_name = 'TEMPLATE_URL';

ALTER TABLE svt_component_types ADD TEMPLATE_URL varchar2(250)
/

alter table svt_component_types add friendly_name varchar2(50)
/
ALTER TABLE SVT_COMPONENT_TYPES MODIFY (friendly_name NOT NULL ENABLE)
/
alter table svt_component_types add name_column varchar2(100)
/
ALTER TABLE SVT_COMPONENT_TYPES MODIFY (name_column NOT NULL ENABLE)
/
alter table svt_component_types add addl_cols varchar2(1000)
/