--liquibase formatted sql
--changeset table_script:SVT_COMPONENT_TYPES stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_COMPONENT_TYPES');
------------------------------------------------------------------------------
--  Creator: Hayden Hudson
--     Date: May 25, 2023
-- Synopsis:
--
-- This table is designed to house the components from WWV_FLOW_DICTIONARY_VIEWS,
-- to which I am linking from my tests
--
------------------------------------------------------------------------------
create table SVT_COMPONENT_TYPES (
  ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  COMPONENT_NAME    VARCHAR2(50) NOT NULL, --WWV_FLOW_DICTIONARY_VIEWS.VIEW_NAME
  COMPONENT_CODE    VARCHAR2(40), -- A WAY TO BRIDGE THE GAP FROM PREVIOUS METHOD
  AVAILABLE_YN      VARCHAR2(1) NOT NULL,
  NT_TYPE_ID        NUMBER, 
  PK_VALUE          VARCHAR2(50),
  PARENT_PK_VALUE   VARCHAR2(50),
  TEMPLATE_URL      VARCHAR2(250),
  FRIENDLY_NAME     VARCHAR2(50),
  NAME_COLUMN       VARCHAR2(100),
  ADDL_COLS         VARCHAR2(1000),
  CREATED           DATE NOT NULL,
  CREATED_BY        VARCHAR2(255 CHAR) NOT NULL,
  UPDATED           DATE NOT NULL,
  UPDATED_BY        VARCHAR2(255 CHAR) NOT NULL
)
/
ALTER TABLE SVT_COMPONENT_TYPES ADD CONSTRAINT UK_COMPONENTNAME UNIQUE(COMPONENT_NAME)
/
ALTER TABLE SVT_COMPONENT_TYPES ADD CONSTRAINT SVT_COMPONENT_TYPES_PK PRIMARY KEY (ID)
/
CREATE INDEX SVT_COMPONENT_TYPES_IDX1 ON SVT_COMPONENT_TYPES (NT_TYPE_ID)
/
 ALTER TABLE SVT_COMPONENT_TYPES MODIFY (NT_TYPE_ID NOT NULL ENABLE)
/
ALTER TABLE SVT_COMPONENT_TYPES MODIFY (FRIENDLY_NAME NOT NULL ENABLE)
/
ALTER TABLE SVT_COMPONENT_TYPES MODIFY (NAME_COLUMN NOT NULL ENABLE)
/
--rollback drop table SVT_COMPONENT_TYPES;