--liquibase formatted sql
--changeset table_script:svt_wcag_test_codes stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('svt_wcag_test_codes');

-- create tables
create table svt_wcag_test_codes (
    id                             number generated by default on null as identity 
                                   constraint svt_wcag_test_code_id_pk primary key,
    test_id                        number
                                   constraint svt_wcag_test_code_test_id_fk
                                   references eba_stds_standard_tests on delete cascade,
    wcag_id                        number
                                   constraint svt_wcag_test_code_wcag_id_fk
                                   references svt_wcag on delete cascade
)
/

-- table index
create index svt_wcag_test_code_i1 on svt_wcag_test_codes (test_id)
/
create index svt_wcag_test_code_i42 on svt_wcag_test_codes (wcag_id)
/


--rollback drop table svt_wcag_test_codes;
