--liquibase formatted sql
--changeset table_script:SVT_STDS_NOTIFICATIONS stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_STDS_NOTIFICATIONS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  SVT_STDS_NOTIFICATIONS.sql
--        Date:  04-Apr-2023 21:36
--     Purpose:  Table creation DDL for table SVT_STDS_NOTIFICATIONS
--               and related objects.
--
--------------------------------------------------------------------------------

  create table svt_stds_notifications 
   (	id                       number generated by default on null as identity, 
      notification_name        varchar2(255 char) not null,
      notification_description varchar2(4000 char),
      notification_type        varchar2(30 char) not null,
      display_sequence         number, 
      display_from             timestamp (6) with local time zone, 
      display_until            timestamp (6) with local time zone, 
      row_version_number       number not null, 
      created                  timestamp (6) with local time zone default systimestamp not null,
      created_by               varchar2(255 char)                 default user not null,
      updated                  timestamp (6) with local time zone default systimestamp not null,
      updated_by               varchar2(255 char)                 default user not null
   ) 
/

  alter table svt_stds_notifications add constraint eba_stdntf_ck1 check (notification_type in ('RED','YELLOW')) enable
/


  alter table svt_stds_notifications add constraint eba_stdntf_pk primary key (id)
  using index (create unique index eba_stdntf_pk_idx on svt_stds_notifications (id) 
  )  enable
/


  alter table svt_stds_notifications add constraint eba_stdntf_uk1 unique (notification_name)
  using index (create unique index eba_stdntf_uk1_idx on svt_stds_notifications (notification_name) 
  )  enable
/


--rollback drop table SVT_STDS_NOTIFICATIONS;
