--liquibase formatted sql
--changeset table_script:SVT_NESTED_TABLE_TYPES stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_NESTED_TABLE_TYPES');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  SVT_NESTED_TABLE_TYPES.sql
--        Date:  10-Apr-2023 19:40
--     Purpose:  Table creation DDL for table SVT_NESTED_TABLE_TYPES
--               and related objects.
--
--------------------------------------------------------------------------------


  create table svt_nested_table_types 
   (	id            number generated by default on null as identity,
      nt_name       varchar2(255 char), 
      example_query clob, 
      object_type   varchar2(55 char),
      created       timestamp (6) with local time zone default systimestamp not null,
      created_by    varchar2(255 char)                 default user not null,
      updated       timestamp (6) with local time zone default systimestamp not null,
      updated_by    varchar2(255 char)                 default user not null
   ) 
/
  alter table svt_nested_table_types add constraint svt_nested_table_t_id_pk primary key (id)
  using index  enable
/

  alter table svt_nested_table_types add constraint svt_nested_table_types_uk1 unique (nt_name)
  using index  enable
/


--rollback drop table SVT_NESTED_TABLE_TYPES;
