--liquibase formatted sql
--changeset table_script:SVT_NESTED_TABLE_TYPES stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_NESTED_TABLE_TYPES');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  SVT_NESTED_TABLE_TYPES.sql
--        Date:  10-Apr-2023 19:40
--     Purpose:  Table creation DDL for table SVT_NESTED_TABLE_TYPES
--               and related objects.
--
--------------------------------------------------------------------------------


  CREATE TABLE SVT_NESTED_TABLE_TYPES 
   (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      NT_NAME VARCHAR2(255 CHAR), 
      EXAMPLE_QUERY CLOB, 
      OBJECT_TYPE VARCHAR2(55 CHAR),
      CREATED DATE, 
      CREATED_BY VARCHAR2(255 CHAR), 
      UPDATED DATE, 
      UPDATED_BY VARCHAR2(255 CHAR)
   ) 
/




  ALTER TABLE SVT_NESTED_TABLE_TYPES MODIFY (UPDATED_BY NOT NULL ENABLE)
/


  ALTER TABLE SVT_NESTED_TABLE_TYPES MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE SVT_NESTED_TABLE_TYPES MODIFY (CREATED NOT NULL ENABLE)
/


  ALTER TABLE SVT_NESTED_TABLE_TYPES MODIFY (UPDATED NOT NULL ENABLE)
/

--precondition-sql-check expectedResult:0 select count(*) from user_constraints where upper(constraint_name)  = 'SVT_NESTED_TABLE_T_ID_PK'

  ALTER TABLE SVT_NESTED_TABLE_TYPES ADD CONSTRAINT SVT_NESTED_TABLE_T_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
/

--precondition-sql-check expectedResult:0 select count(*) from user_constraints where upper(constraint_name)  = 'SVT_NESTED_TABLE_TYPES_UK1'

  ALTER TABLE SVT_NESTED_TABLE_TYPES ADD CONSTRAINT SVT_NESTED_TABLE_TYPES_UK1 UNIQUE (NT_NAME)
  USING INDEX  ENABLE
/


--rollback drop table SVT_NESTED_TABLE_TYPES;
