--liquibase formatted sql
--changeset table_script:SVT_AUDIT_ACTIONS stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_AUDIT_ACTIONS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  SVT_AUDIT_ACTIONS.sql
--        Date:  10-Apr-2023 19:39
--     Purpose:  Table creation DDL for table SVT_AUDIT_ACTIONS
--               and related objects.
--
--------------------------------------------------------------------------------


  create table svt_audit_actions 
   (	id                   number generated by default on null as identity,
      action_name          varchar2(255 char), 
      include_in_report_yn varchar2(1 char) not null,
      created              timestamp (6) with local time zone default systimestamp not null,
      created_by           varchar2(255 char)                 default user not null,
      updated              timestamp (6) with local time zone default systimestamp not null,
      updated_by           varchar2(255 char)                 default user not null
   ) 
/

  alter table svt_audit_actions add constraint svt_adtact_pk primary key (id)
  using index (create unique index svt_adtact_pk_idx on svt_audit_actions (id) 
  )  enable
/

--rollback drop table SVT_AUDIT_ACTIONS;