--liquibase formatted sql
--changeset table_script:svt_test_timing stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('svt_test_timing');
create table svt_test_timing (
    id                             number generated by default on null as identity 
                                   constraint svt_test_timing_id_pk primary key,
    test_code                      varchar2(100 char),
    elapsed_seconds                number,
    created                        date default sysdate not null
);
--rollback drop table svt_test_timing;
