--liquibase formatted sql
--changeset table_script:SVT_PLSQL_APEX_AUDIT stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_PLSQL_APEX_AUDIT');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  SVT_PLSQL_APEX_AUDIT.sql
--        Date:  10-Apr-2023 19:41
--     Purpose:  Table creation DDL for table SVT_PLSQL_APEX_AUDIT
--               and related objects.
--
--------------------------------------------------------------------------------


  create table svt_plsql_apex_audit 
   (	id                      number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder  nocycle  nokeep  noscale , 
		issue_category             varchar2(10 char), 
		application_id             number, 
		page_id                    number, 
		line                       number, 
		object_name                varchar2(255 char), 
		object_type                varchar2(31 char), 
		code                       varchar2(4000 char), 
		validation_failure_message varchar2(4000 char), 
		apex_created_by            varchar2(255 char), 
		apex_created_on            date, 
		apex_last_updated_by       varchar2(255 char), 
		apex_last_updated_on       date, 
		assignee                   varchar2(255 char), 
		notes                      varchar2(4000 char), 
		action_id                  number, 
		apex_issue_id              number, 
		issue_title                varchar2(1000 char), 
		apex_issue_title_suffix    varchar2(100 char), 
		owner                      varchar2(50 char), 
		test_code                  varchar2(100 char), 
		unqid                      varchar2(1000 char), 
		legacy_yn                  varchar2(1 char),
		component_id               number,
		parent_component_id        number,
		created                    date               default sysdate not null,
		created_by                 varchar2(255 char) default user not null,
		updated                    date               default sysdate not null,
		updated_by                 varchar2(255 char) default user not null
   )  enable row movement 
/

  create index svt_plapad_idx1 on svt_plsql_apex_audit (action_id) 
/

  alter table svt_plsql_apex_audit add constraint svt_plapad_uk2 unique (unqid)
  using index  enable
/

  alter table svt_plsql_apex_audit add constraint svt_plapad_pk primary key (id)
  using index (create unique index svt_plapad_pk_idx on svt_plsql_apex_audit (id) 
  )  enable
/

create index svt_plapad_idx2 on svt_plsql_apex_audit(test_code)
/
create index svt_plapad_idx3 on svt_plsql_apex_audit(application_id)
/
--rollback drop table SVT_PLSQL_APEX_AUDIT;