--liquibase formatted sql
--changeset table_script:svt_compatibility stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('svt_compatibility');

/* based on APPLICATION.COMPATIBILITY_MODE from app 4000  */
create table svt_compatibility (
    id                   number generated by default on null as identity 
                         constraint svt_compatibility_id_pk primary key,
    display_order        number             not null,
    compatibility_mode   varchar2(4 char)   not null,
    compatibility_desc   varchar2(400 char) not null,
    type_name            varchar2(10 char)  not null,
    created              timestamp (6) with local time zone default systimestamp not null,
    created_by           varchar2(255 char)                 default user not null,
    updated              timestamp (6) with local time zone default systimestamp not null,
    updated_by           varchar2(255 char)                 default user not null
)
/
--rollback drop table svt_compatibility;
