--liquibase formatted sql
--changeset table_script:SVT_AUDIT_ON_AUDIT stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_AUDIT_ON_AUDIT');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  SVT_AUDIT_ON_AUDIT.sql
--        Date:  10-Apr-2023 19:40
--     Purpose:  Table creation DDL for table SVT_AUDIT_ON_AUDIT
--               and related objects.
--
--------------------------------------------------------------------------------


  create table svt_audit_on_audit 
   (	id                         number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder  nocycle  nokeep  noscale , 
      unqid                      varchar2(1000 char) not null, 
      action_name                varchar2(100 char) not null, 
      test_code                  varchar2(100 char),
      audit_id                   number,
      validation_failure_message varchar2(4000 char),
      app_id                     number,
      page_id                    number,
      component_id               number,
      assignee                   varchar2(255 char),
      line                       number, 
		  object_name                varchar2(255 char), 
		  object_type                varchar2(31 char), 
		  code                       varchar2(255 char), 
      delete_reason              varchar2(31 char),
      created                    timestamp (6) with local time zone default systimestamp not null,
      created_by                 varchar2(255 char)                 default user not null
   ) 
/

  alter table svt_audit_on_audit add constraint svt_adt_pk primary key (id)
  using index (create unique index svt_adt_pk_idx on svt_audit_on_audit (id) 
  )  enable
/

--rollback drop table SVT_AUDIT_ON_AUDIT;