--liquibase formatted sql
--changeset table_script:svt_compatibility stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('svt_compatibility');

/* based on APPLICATION.COMPATIBILITY_MODE from app 4000  */
CREATE TABLE SVT_COMPATIBILITY (
    ID                             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
                                   CONSTRAINT SVT_COMPATIBILITY_ID_PK PRIMARY KEY,
    DISPLAY_ORDER                  NUMBER             NOT NULL,
    COMPATIBILITY_MODE             VARCHAR2(4 CHAR)   NOT NULL,
    COMPATIBILITY_DESC             VARCHAR2(400 CHAR) NOT NULL,
    TYPE_NAME                      VARCHAR2(10 CHAR)  NOT NULL,
    CREATED                        DATE NOT NULL,
    CREATED_BY                     VARCHAR2(255 CHAR) NOT NULL,
    UPDATED                        DATE NOT NULL,
    UPDATED_BY                     VARCHAR2(255 CHAR) NOT NULL
)
/
--rollback drop table svt_compatibility;
