--liquibase formatted sql
--changeset table_script:SVT_COMPONENT_TYPES stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_COMPONENT_TYPES');
------------------------------------------------------------------------------
--  Creator: Hayden Hudson
--     Date: May 25, 2023
-- Synopsis:
--
-- This table is designed to house the components from WWV_FLOW_DICTIONARY_VIEWS,
-- to which I am linking from my tests
--
------------------------------------------------------------------------------
create table svt_component_types (
  id                number generated by default on null as identity,
  component_name    varchar2(50 char) not null,
  component_code    varchar2(40 char),
  available_yn      varchar2(1 char) not null,
  nt_type_id        number not null, 
  pk_value          varchar2(50 char),
  parent_pk_value   varchar2(50 char),
  template_url      varchar2(250 char),
  friendly_name     varchar2(50 char) not null,
  name_column       varchar2(100 char) not null,
  addl_cols         varchar2(1000 char),
  created           timestamp (6) with local time zone default systimestamp not null,
  created_by        varchar2(255 char)                 default user not null,
  updated           timestamp (6) with local time zone default systimestamp not null,
  updated_by        varchar2(255 char)                 default user not null
)
/
alter table svt_component_types add constraint uk_componentname unique(component_name)
/
alter table svt_component_types add constraint svt_component_types_pk primary key (id)
/
create index svt_component_types_idx1 on svt_component_types (nt_type_id)
/
--rollback drop table SVT_COMPONENT_TYPES;