--liquibase formatted sql
--changeset table_script:SVT_SERT_HOW_TO_FIX stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_SERT_HOW_TO_FIX');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  SVT_SERT_HOW_TO_FIX.sql
--        Date:  10-Apr-2023 18:40
--     Purpose:  Table creation DDL for table SVT_SERT_HOW_TO_FIX
--               and related objects.
--
--------------------------------------------------------------------------------


  CREATE TABLE SVT_SERT_HOW_TO_FIX 
   (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
      ATTRIBUTE_ID NUMBER DEFAULT '1', 
      INFO CLOB, 
      FIX CLOB, 
      SOURCE_INFO_FIX_MD5 VARCHAR2(100 CHAR), 
      COLLECTION_NAME VARCHAR2(255 CHAR), 
      TEST_ID NUMBER,
      CREATED DATE, 
      CREATED_BY VARCHAR2(255 CHAR), 
      UPDATED DATE, 
      UPDATED_BY VARCHAR2(255 CHAR)
   ) 
/

  CREATE INDEX SVT_SERT_HOW_TO_FIX_IDX1 ON SVT_SERT_HOW_TO_FIX (TEST_ID) 
  
/

  ALTER TABLE SVT_SERT_HOW_TO_FIX MODIFY (CREATED NOT NULL ENABLE)
/


  ALTER TABLE SVT_SERT_HOW_TO_FIX MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE SVT_SERT_HOW_TO_FIX MODIFY (UPDATED NOT NULL ENABLE)
/


  ALTER TABLE SVT_SERT_HOW_TO_FIX MODIFY (UPDATED_BY NOT NULL ENABLE)
/


  ALTER TABLE SVT_SERT_HOW_TO_FIX ADD CONSTRAINT SVT_HOW_TO_FIX_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
/


--rollback drop table SVT_SERT_HOW_TO_FIX;
