--liquibase formatted sql
--changeset table_script:SVT_STDS_TESTS_LIB stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_STDS_TESTS_LIB');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  SVT_STDS_TESTS_LIB.sql
--        Date:  08-Jun-2023 21:55
--     Purpose:  Table creation DDL for table SVT_STDS_TESTS_LIB
--               and related objects.
-- preserves contents of SVT_STDS_STANDARD_TESTS for deployment
--
--------------------------------------------------------------------------------
  
  create table svt_stds_tests_lib 
   (	id                    number generated by default on null as identity 
                            minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 
                            cache 20 noorder  nocycle  nokeep  noscale, 
	    standard_id           number, 
	    test_name             varchar2(64 char), 
	    query_clob            clob, 
	    test_code             varchar2(100 char) not null, 
	    active_yn             varchar2(1 char), 
	    mv_dependency         varchar2(100 char), 
	    svt_component_type_id number, 
	    test_id               number,
      explanation           varchar2(4000 char),
      fix                   clob,
      level_id              number,
      version_number        number not null,
      version_db            varchar2(55 char) not null
   ) 
/

  alter table svt_stds_tests_lib add constraint svt_ststts_lib_pk primary key (id)
  using index (create unique index svt_ststts_lib_idx on svt_stds_tests_lib (id) 
  )  enable
/

  alter table svt_stds_tests_lib add constraint svt_ststts_lib_uk1 unique (test_code)
  using index  enable
/

--rollback drop table SVT_STDS_TESTS_LIB;
