--liquibase formatted sql
--changeset table_script:SVT_STDS_STANDARDS stripComments:false runOnChange:true
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('SVT_STDS_STANDARDS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  SVT_STDS_STANDARDS.sql
--        Date:  07-Apr-2023 22:36
--     Purpose:  Table creation DDL for table SVT_STDS_STANDARDS
--               and related objects.
--
--------------------------------------------------------------------------------


  create table svt_stds_standards 
   (	id                    number generated by default on null as identity, 
      standard_name         varchar2(64 char) not null,
      description           varchar2(4000 char),
      primary_developer     varchar2(255 char),
      implementation        clob, 
      date_started          timestamp (6) with local time zone default localtimestamp not null, 
      standard_group        varchar2(32 char),
      active_yn             varchar2(1 char) default 'Y' not null,
      compatibility_mode_id number not null,
      parent_standard_id    number,
      created               timestamp (6) with local time zone default systimestamp not null,
      created_by            varchar2(255 char)                 default user not null,
      updated               timestamp (6) with local time zone default systimestamp not null,
      updated_by            varchar2(255 char)                 default user not null
   ) 
/
 
  alter table svt_stds_standards add constraint svt_stdstn_pk primary key (id)
  using index (create unique index svt_stdstn_pk_idx on svt_stds_standards (id) 
  )  enable
/

alter table svt_stds_standards add constraint svt_stdstn_uk unique (standard_name, compatibility_mode_id)
/

  alter table svt_stds_standards add constraint svt_stdstn_uk2 unique (id, parent_standard_id)
  using index  enable
/

create index svt_stdstn_idx1 on svt_stds_standards (compatibility_mode_id)
/

create index svt_stdstn_idx2 on svt_stds_standards (parent_standard_id)
/

--rollback drop table SVT_STDS_STANDARDS;