---
- # ====== Automation: 3. [Hourly - 40 min past] Manage APEX Iss
  id: 228722607695252393
  identification: 
    name: 3. [Hourly - 40 min past] Manage APEX Issues
    static-id: manage-apex-issues

  execution: 
    type: Scheduled
    schedule-expression: FREQ=HOURLY;INTERVAL=1;BYMINUTE=40
    schedule-status: Active
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Disable Automation

  comments: 
    comments: FREQ=HOURLY;INTERVAL=1;BYMINUTE=40

  actions: 
  - # ====== Action: manage_apex_issues ==========================
    id: 228723006205252395
    identification: 
      name: manage_apex_issues
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: svt_apex_issue_util.manage_apex_issues;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

- # ====== Automation: 6. [Daily] Validate APEX Version ========
  id: 228724649600576958
  identification: 
    name: 6. [Daily] Validate APEX Version
    static-id: validate-apex-version

  execution: 
    type: Scheduled
    schedule-expression: FREQ=DAILY;INTERVAL=1;BYHOUR=0;BYMINUTE=0
    schedule-status: Active
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Disable Automation

  comments: 
    comments: FREQ=DAILY;INTERVAL=1;BYHOUR=0;BYMINUTE=0

  actions: 
  - # ====== Action: Send email ==================================
    id: 228724935225576959
    identification: 
      name: Send email
      type: Send E-Mail

    settings: 
      from: '&APP_EMAIL.'
      to: hayden.h.hudson@oracle.com
      subject: The Oracle APEX Version is out-of-date
      body-plain-text: You must update oracle_apex_version & svt_flow_issues.
      send-immediately: false

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

    server-side-condition: 
      type: Function Body
      language: PL/SQL
      pl/sql-function-body: |
        begin
        svt_apex_issue_util.hard_correct_svt_issues;
        return false;
        exception when others then
        return true;
        end;
      execute-condition: For Each Row

- # ====== Automation: 1. [Hourly on the dot] Refresh Materializ
  id: 229077435889682548
  identification: 
    name: 1. [Hourly on the dot] Refresh Materialized Views
    static-id: refresh-all-materialized-views

  execution: 
    type: Scheduled
    schedule-expression: FREQ=HOURLY;INTERVAL=1;BYMINUTE=0
    schedule-status: Active
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Disable Automation

  comments: 
    comments: FREQ=HOURLY;INTERVAL=1;BYMINUTE=0

  actions: 
  - # ====== Action: refresh mv ==================================
    id: 229103885951687690
    identification: 
      name: refresh mv
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
          SVT_MV_UTIL.refresh_mv();
        end;

    execution: 
      sequence: 20

    error: 
      stop-execution-on-error: true

- # ====== Automation: 8.[Every 6 hours -  55 min past] Delete s
  id: 263521704929577710
  identification: 
    name: 8.[Every 6 hours -  55 min past] Delete stale issues
    static-id: 8-nightly-delete-stale-issues

  execution: 
    type: Scheduled
    schedule-expression: FREQ=HOURLY;INTERVAL=6;BYMINUTE=55
    schedule-status: Active
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Ignore

  comments: 
    comments: FREQ=HOURLY;INTERVAL=6;BYMINUTE=55

  actions: 
  - # ====== Action: svt_plsql_apex_audit_api.delete_stale =======
    id: 263522004995577712
    identification: 
      name: svt_plsql_apex_audit_api.delete_stale
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
            svt_plsql_apex_audit_api.delete_stale;
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

- # ====== Automation: 7. [Nightly @ midnight] Refresh Cumulativ
  id: 280867419610309873
  identification: 
    name: 7. [Nightly @ midnight] Refresh Cumulative Issues count
    static-id: 7-nightly-refresh-cumulative-issues-count

  execution: 
    type: Scheduled
    schedule-expression: FREQ=DAILY;INTERVAL=1;BYHOUR=0;BYMINUTE=0
    schedule-status: Active
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Ignore

  comments: 
    comments: FREQ=DAILY;INTERVAL=1;BYHOUR=0;BYMINUTE=0

  actions: 
  - # ====== Action: dbms_mview.refresh  MV_ISSUES_CREATED_BY_DAY 
    id: 280867738134309874
    identification: 
      name: dbms_mview.refresh  MV_ISSUES_CREATED_BY_DAY
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
          dbms_mview.refresh ('MV_ISSUES_CREATED_BY_DAY');
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

- # ====== Automation: 9. [Every morning] manage timing audits =
  id: 293514005069795938
  identification: 
    name: 9. [Every morning] manage timing audits
    static-id: 9-clear-old-timing-records

  execution: 
    type: Scheduled
    schedule-expression: FREQ=DAILY;INTERVAL=1;BYHOUR=6;BYMINUTE=0
    schedule-status: Active
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Ignore

  actions: 
  - # ====== Action: svt_test_timing_api.purge_old ===============
    id: 293514390776795945
    identification: 
      name: svt_test_timing_api.purge_old
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
            svt_test_timing_api.purge_old;
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

  - # ====== Action: eba_stds_standards_api.update_test_avg_time =
    id: 293515188244870708
    identification: 
      name: eba_stds_standards_api.update_test_avg_time
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
            eba_stds_standards_api.update_test_avg_time;
        end;

    execution: 
      sequence: 20

    error: 
      stop-execution-on-error: true

- # ====== Automation: 10. [Every night at 1AM] Recompile with P
  id: 344919856023132125
  identification: 
    name: 10. [Every night at 1AM] Recompile with PLScope
    static-id: 10-recompile-with-plscope

  execution: 
    type: Scheduled
    schedule-expression: FREQ=DAILY;INTERVAL=1;BYHOUR=1;BYMINUTE=0
    schedule-status: Active
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Ignore

  actions: 
  - # ====== Action: svt_audit_util.recompile_all_schemas_w_plscop
    id: 344920186711132127
    identification: 
      name: svt_audit_util.recompile_all_schemas_w_plscope
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
            svt_audit_util.recompile_all_schemas_w_plscope;
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

- # ====== Automation: 2. [Bi-Hourly  - 10 min past] Issue Snaps
  id: 552097788301127980
  identification: 
    name: 2. [Bi-Hourly  - 10 min past] Issue Snapshot in DB audit table
    static-id: big-job

  execution: 
    type: Scheduled
    schedule-expression: FREQ=HOURLY;INTERVAL=2;BYMINUTE=10
    schedule-status: Active
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Disable Automation

  comments: 
    comments: |
      new : FREQ=HOURLY;INTERVAL=2;BYMINUTE=10
      old : FREQ=HOURLY;INTERVAL=1;BYMINUTE=10

  actions: 
  - # ====== Action: record_daily_issue_snapshot =================
    id: 552098101108127996
    identification: 
      name: record_daily_issue_snapshot
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: svt_audit_util.record_daily_issue_snapshot;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

- # ====== Automation: 5. [Daily] Send Admin Email =============
  id: 661528361206157359
  identification: 
    name: 5. [Daily] Send Admin Email
    static-id: send-admin-email

  execution: 
    type: Scheduled
    schedule-expression: FREQ=DAILY;INTERVAL=1;BYHOUR=11;BYMINUTE=0
    schedule-status: Active
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Disable Automation

  comments: 
    comments: FREQ=DAILY;INTERVAL=1;BYHOUR=11;BYMINUTE=0

  actions: 
  - # ====== Action: send email ==================================
    id: 661528727584157364
    identification: 
      name: send email
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
            svt_monitoring.send_update(p_days_since => 2,
                                       p_override_email => 'hayden.h.hudson@oracle.com');
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

