---
- # ====== Automation: 3. [Hourly - 40 min past] Manage APEX Iss
  id: 276315485800312540
  identification: 
    name: 3. [Hourly - 40 min past] Manage APEX Issues
    static-id: manage-apex-issues

  execution: 
    type: Scheduled
    schedule-expression: FREQ=HOURLY;INTERVAL=1;BYMINUTE=40
    schedule-status: Disabled
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Disable Automation

  server-side-condition: 
    type: Expression
    language: PL/SQL
    pl/sql-expression: oracle_apex_version.c_apex_issue_access

  comments: 
    comments: FREQ=HOURLY;INTERVAL=1;BYMINUTE=40

  actions: 
  - # ====== Action: manage_apex_issues ==========================
    id: 276315884310312542
    identification: 
      name: manage_apex_issues
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        declare
        t1 timestamp; 
        t2 timestamp; 
        l_message varchar2(1000);
        begin
          t1 := systimestamp; 
          svt_apex_issue_util.manage_apex_issues(p_message => l_message);
          t2 := systimestamp; 
          apex_automation.log_info( p_message => 
                                    apex_string.format( '%0 [in %1 second(s)]',
                                        p0=> l_message,
                                        p1 => extract( second from (t2-t1) )
                                    )
                                   );
          commit;
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

    server-side-condition: 
      type: Expression
      language: PL/SQL
      pl/sql-expression: oracle_apex_version.c_apex_issue_access
      execute-condition: For Each Row

- # ====== Automation: 6. [Daily] Validate APEX Version ========
  id: 276317527705637105
  identification: 
    name: 6. [Daily] Validate APEX Version
    static-id: validate-apex-version

  execution: 
    type: Scheduled
    schedule-expression: FREQ=DAILY;INTERVAL=1;BYHOUR=0;BYMINUTE=0
    schedule-status: Disabled
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Disable Automation

  server-side-condition: 
    type: Expression
    language: PL/SQL
    pl/sql-expression: oracle_apex_version.c_apex_issue_access

  comments: 
    comments: FREQ=DAILY;INTERVAL=1;BYHOUR=0;BYMINUTE=0

  actions: 
  - # ====== Action: Send email ==================================
    id: 276317813330637106
    identification: 
      name: Send email
      type: Send E-Mail

    settings: 
      from: '&APP_EMAIL.'
      to: hayden.h.hudson@oracle.com
      subject: The Oracle APEX Version is out-of-date
      body-plain-text: You must update oracle_apex_version & svt_flow_issues.
      send-immediately: false

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

    server-side-condition: 
      type: Function Body
      language: PL/SQL
      pl/sql-function-body: |
        begin
        svt_apex_issue_util.hard_correct_svt_issues;
        return false;
        exception when others then
        return true;
        end;
      execute-condition: For Each Row

- # ====== Automation: 1. [Hourly on the dot] Refresh Materializ
  id: 276670313994742695
  identification: 
    name: 1. [Hourly on the dot] Refresh Materialized Views
    static-id: refresh-all-materialized-views

  execution: 
    type: Scheduled
    schedule-expression: FREQ=HOURLY;INTERVAL=1;BYMINUTE=0
    schedule-status: Disabled
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Disable Automation

  comments: 
    comments: FREQ=HOURLY;INTERVAL=1;BYMINUTE=0

  actions: 
  - # ====== Action: refresh mv ==================================
    id: 276696764056747837
    identification: 
      name: refresh mv
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
          SVT_MV_UTIL.refresh_mv();
        end;

    execution: 
      sequence: 20

    error: 
      stop-execution-on-error: true

- # ====== Automation: 8. [Every 6 hours -  55 min past] Delete 
  id: 311114583034637857
  identification: 
    name: 8. [Every 6 hours -  55 min past] Delete stale issues
    static-id: 8-nightly-delete-stale-issues

  execution: 
    type: Scheduled
    schedule-expression: FREQ=HOURLY;INTERVAL=6;BYMINUTE=55
    schedule-status: Disabled
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Ignore

  comments: 
    comments: FREQ=HOURLY;INTERVAL=6;BYMINUTE=55

  actions: 
  - # ====== Action: svt_plsql_apex_audit_api.delete_stale =======
    id: 311114883100637859
    identification: 
      name: svt_plsql_apex_audit_api.delete_stale
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        declare
        t1 timestamp; 
        t2 timestamp; 
        l_deleted_count pls_integer;
        begin
          t1 := systimestamp; 
          svt_plsql_apex_audit_api.delete_stale(p_deleted_count => l_deleted_count);
          if l_deleted_count > 0 then
              t2 := systimestamp; 
              apex_automation.log_info( p_message => 
                                        apex_string.format( 'Deleted %0 violation(s) in %1 second(s)',
                                          p0=> l_deleted_count,
                                          p1 => extract( second from (t2-t1) )
                                        )
                                      );
          end if;
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

- # ====== Automation: 7. [Nightly @ midnight] Refresh Cumulativ
  id: 328460297715370020
  identification: 
    name: 7. [Nightly @ midnight] Refresh Cumulative Issues count
    static-id: 7-nightly-refresh-cumulative-issues-count

  execution: 
    type: Scheduled
    schedule-expression: FREQ=DAILY;INTERVAL=1;BYHOUR=0;BYMINUTE=0
    schedule-status: Disabled
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Ignore

  comments: 
    comments: FREQ=DAILY;INTERVAL=1;BYHOUR=0;BYMINUTE=0

  actions: 
  - # ====== Action: dbms_mview.refresh  MV_SVT_ISSUES_CREATED_BY_
    id: 328460616239370021
    identification: 
      name: dbms_mview.refresh  MV_SVT_ISSUES_CREATED_BY_DAY
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
          dbms_mview.refresh ('MV_SVT_ISSUES_CREATED_BY_DAY');
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

- # ====== Automation: 9. [Every morning] manage timing audits =
  id: 341106883174856085
  identification: 
    name: 9. [Every morning] manage timing audits
    static-id: 9-clear-old-timing-records

  execution: 
    type: Scheduled
    schedule-expression: FREQ=DAILY;INTERVAL=1;BYHOUR=6;BYMINUTE=0
    schedule-status: Disabled
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Ignore

  actions: 
  - # ====== Action: svt_test_timing_api.purge_old ===============
    id: 341107268881856092
    identification: 
      name: svt_test_timing_api.purge_old
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
            svt_test_timing_api.purge_old;
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

  - # ====== Action: svt_stds_standards_api.update_test_avg_time =
    id: 341108066349930855
    identification: 
      name: svt_stds_standards_api.update_test_avg_time
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
            svt_stds_standards_api.update_test_avg_time;
        end;

    execution: 
      sequence: 20

    error: 
      stop-execution-on-error: true

- # ====== Automation: 10. [Every night at 1AM] Recompile with P
  id: 392512734128192272
  identification: 
    name: 10. [Every night at 1AM] Recompile with PLScope
    static-id: 10-recompile-with-plscope

  execution: 
    type: Scheduled
    schedule-expression: FREQ=DAILY;INTERVAL=1;BYHOUR=1;BYMINUTE=0
    schedule-status: Disabled
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Ignore

  actions: 
  - # ====== Action: svt_audit_util.recompile_all_schemas_w_plscop
    id: 392513064816192274
    identification: 
      name: svt_audit_util.recompile_all_schemas_w_plscope
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
            svt_audit_util.recompile_all_schemas_w_plscope;
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

- # ====== Automation: 4. [Hourly 25 min past] Delete inactive v
  id: 411754420998088091
  identification: 
    name: 4. [Hourly 25 min past] Delete inactive violations
    static-id: 4-delete-inactive-violations

  execution: 
    type: Scheduled
    schedule-expression: FREQ=HOURLY;INTERVAL=1;BYMINUTE=25
    schedule-status: Disabled
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Ignore

  comments: 
    comments: FREQ=HOURLY;INTERVAL=1;BYMINUTE=25

  actions: 
  - # ====== Action: svt_plsql_apex_audit_api.delete_inactive ====
    id: 411754722445088094
    identification: 
      name: svt_plsql_apex_audit_api.delete_inactive
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        declare
        t1 timestamp; 
        t2 timestamp; 
        l_deleted_count pls_integer;
        begin
          t1 := systimestamp; 
          svt_plsql_apex_audit_api.delete_inactive(p_deleted_count => l_deleted_count);
          if l_deleted_count > 0 then
              t2 := systimestamp; 
              apex_automation.log_info( p_message => 
                                        apex_string.format( 'Deleted %0 violation(s) in %1 second(s)',
                                          p0=> l_deleted_count,
                                          p1 => extract( second from (t2-t1) )
                                        )
                                      );
          end if;
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

- # ====== Automation: 2. [Bi-Hourly  - 10 min past] Issue Snaps
  id: 599690666406188127
  identification: 
    name: 2. [Bi-Hourly  - 10 min past] Issue Snapshot in DB audit table
    static-id: big-job

  execution: 
    type: Scheduled
    schedule-expression: FREQ=HOURLY;INTERVAL=2;BYMINUTE=10
    schedule-status: Disabled
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Disable Automation

  comments: 
    comments: |
      new : FREQ=HOURLY;INTERVAL=2;BYMINUTE=10
      old : FREQ=HOURLY;INTERVAL=1;BYMINUTE=10

  actions: 
  - # ====== Action: record_daily_issue_snapshot =================
    id: 599690979213188143
    identification: 
      name: record_daily_issue_snapshot
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        declare
        t1 timestamp; 
        t2 timestamp; 
        l_message varchar2(1000);
        begin
          t1 := systimestamp; 
          svt_audit_util.record_daily_issue_snapshot(p_message => l_message);
          t2 := systimestamp; 
          apex_automation.log_info( p_message => 
                                    apex_string.format( '%0 [in %1 second(s)]',
                                        p0=> l_message,
                                        p1 => extract( second from (t2-t1) )
                                    )
                                   );
          commit;
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

- # ====== Automation: 5. [Daily] Send Admin Email =============
  id: 709121239311217506
  identification: 
    name: 5. [Daily] Send Admin Email
    static-id: send-admin-email

  execution: 
    type: Scheduled
    schedule-expression: FREQ=DAILY;INTERVAL=1;BYHOUR=11;BYMINUTE=0
    schedule-status: Disabled
    actions-initiated-on: Always

  action-execution: 
    action-error-handling: Disable Automation

  server-side-condition: 
    type: Expression
    language: PL/SQL
    pl/sql-expression: |
      case when svt_preferences.get('SVT_EMAIL_API') is null
           then false
           when svt_preferences.get('SVT_EMAIL_API') = 'NA'
           then false
           else true
           end

  comments: 
    comments: FREQ=DAILY;INTERVAL=1;BYHOUR=11;BYMINUTE=0

  actions: 
  - # ====== Action: send email ==================================
    id: 709121605689217511
    identification: 
      name: send email
      type: Execute Code

    source: 
      location: Local Database
      language: PL/SQL
      pl/sql-code: |
        begin
            svt_monitoring.send_update(p_days_since => 2,
                                       p_override_email => 'hayden.h.hudson@oracle.com');
        end;

    execution: 
      sequence: 10

    error: 
      stop-execution-on-error: true

    server-side-condition: 
      type: Expression
      language: PL/SQL
      pl/sql-expression: |
        case when svt_preferences.get('SVT_EMAIL_API') is null
             then false
             when svt_preferences.get('SVT_EMAIL_API') = 'NA'
             then false
             else true
             end
      execute-condition: For Each Row

