---
- # ====== Search Configuration: V_SVT_NAV_MENU ================
  id: 52465087916389448
  identification: 
    name: V_SVT_NAV_MENU

  source: 
    search-type: Simple (APEX Data Source)
    location: Local Database
    type: SQL Query
    sql-query: |
      select list_entry_id,
             entry_text, 
             entry_url,
             entry_attribute_01,
             entry_image
      from V_SVT_NAV_MENU
    searchable-columns: 'ENTRY_TEXT:ENTRY_ATTRIBUTE_01'

  order-by: 
    order-by-clause: entry_text

  column-mapping: 
    primary-key-1-column-name: LIST_ENTRY_ID
    title-column-name: ENTRY_TEXT
    description-column-name: ENTRY_ATTRIBUTE_01

  link: 
    type: Redirect to URL
    target: '&ENTRY_URL.'

  icon-and-badge: 
    icon-source: Icon Class Column
    icon-column: ENTRY_IMAGE

  advanced: 
    static-id: v_svt_nav_menu

- # ====== Search Configuration: Standard Groups ===============
  id: 147803942933237929
  identification: 
    name: Standard Groups

  source: 
    search-type: Simple (APEX Data Source)
    location: Local Database
    type: Table / View
    table-owner: Parsing Schema
    table-name: EBA_STDS_STANDARDS
    where-clause: active_yn = 'Y'
    searchable-columns: 'STANDARD_NAME:DESCRIPTION'

  order-by: 
    order-by-clause: standard_name

  column-mapping: 
    primary-key-1-column-name: ID
    title-column-name: STANDARD_NAME
    description-column-name: DESCRIPTION

  link: 
    type: Redirect to Page in this Application
    target: 
      url: 'f?p=&APP_ID.:5:&APP_SESSION.::&DEBUG.:RP,5:P5_ID:&ID.'
      page: 5 # V_EBA_STDS_STANDARD_TESTS
      clear-cache: RP,5
      values: 
        p5_id: '&ID.'

  icon-and-badge: 
    icon-source: Initials

  column-formatting: 
    html-expression: |
      <div class="a-ResultsItem &RESULT_CSS_CLASSES!ATTR.">
       <div class="a-ResultItem-initials u-color-var">&INITIALS.</div>
        <div class="a-ResultsItem-content">
          <div class="a-ResultsItem-header">
            <span class="a-ResultsItem-title"><a href="f?p=&APP_ID.:5:&SESSION.::::P5_ID:&ID.">&STANDARD_NAME.</a></span>
            <span class="a-ResultsItem-badge">standard</span>
          </div>
          <div class="a-ResultsItem-description">&DESCRIPTION.</div>
        </div>
      </div>

  advanced: 
    static-id: standard_groups

  security: 
    authorization-scheme: READER RIGHTS # 48893993399820863

- # ====== Search Configuration: Tests =========================
  id: 147805726929267423
  identification: 
    name: Tests

  source: 
    search-type: Simple (APEX Data Source)
    location: Local Database
    type: Table / View
    table-owner: Parsing Schema
    table-name: EBA_STDS_STANDARD_TESTS
    searchable-columns: 'EXPLANATION:MV_DEPENDENCY:TEST_NAME:TEST_CODE'

  order-by: 
    order-by-clause: test_name

  column-mapping: 
    primary-key-1-column-name: ID
    title-column-name: TEST_NAME
    description-column-name: EXPLANATION
    custom-column-name-1: MV_DEPENDENCY

  icon-and-badge: 
    icon-source: Initials

  column-formatting: 
    html-expression: |
      <div class="a-ResultsItem &RESULT_CSS_CLASSES!ATTR.">
       <div class="a-ResultItem-initials u-color-var">&INITIALS.</div>
        <div class="a-ResultsItem-content">
          <div class="a-ResultsItem-header">
            <span class="a-ResultsItem-title"><a href="f?p=&APP_ID.:1:&SESSION.::::P1_TEST_CODE:&TEST_CODE.">&TEST_NAME.</a></span>
            <span class="a-ResultsItem-badge">test</span>
          </div>
          <div class="a-ResultsItem-description">&EXPLANATION.</div>
          <div class="a-ResultsItem-attributes">
            <span class="a-ResultsItem-attribute">&TEST_CODE.</span>
          </div>
          {if ?MV_DEPENDENCY/}<div class="a-ResultsItem-misc">&MV_DEPENDENCY.</div>{endif/}
        </div>
      </div>

  advanced: 
    static-id: tests

  security: 
    authorization-scheme: READER RIGHTS # 48893993399820863

