--liquibase formatted sql
--changeset table_script:DEV_TABCOL_RELEASE_SNAPSHOTS stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('DEV_TABCOL_RELEASE_SNAPSHOTS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  DEV_TABCOL_RELEASE_SNAPSHOTS.sql
--        Date:  07-Apr-2023 16:04
--     Purpose:  Table creation DDL for table DEV_TABCOL_RELEASE_SNAPSHOTS
--               and related objects.
--
--------------------------------------------------------------------------------


  CREATE TABLE DEV_TABCOL_RELEASE_SNAPSHOTS 
   (	RELEASE_LABEL VARCHAR2(12 CHAR), 
	TABLE_NAME VARCHAR2(60 CHAR), 
	COLUMN_NAME VARCHAR2(60 CHAR), 
	DATA_TYPE VARCHAR2(60 CHAR), 
	DATA_LENGTH NUMBER, 
	DATA_PRECISION NUMBER, 
	DATA_SCALE NUMBER, 
	COLUMN_ID NUMBER, 
	NULLABLE VARCHAR2(1 CHAR), 
	CREATED_ON TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED_ON TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255)
   ) 
/




  ALTER TABLE DEV_TABCOL_RELEASE_SNAPSHOTS MODIFY (RELEASE_LABEL NOT NULL ENABLE)
/


  ALTER TABLE DEV_TABCOL_RELEASE_SNAPSHOTS MODIFY (TABLE_NAME NOT NULL ENABLE)
/


  ALTER TABLE DEV_TABCOL_RELEASE_SNAPSHOTS MODIFY (COLUMN_NAME NOT NULL ENABLE)
/


  ALTER TABLE DEV_TABCOL_RELEASE_SNAPSHOTS MODIFY (CREATED_ON NOT NULL ENABLE)
/


  ALTER TABLE DEV_TABCOL_RELEASE_SNAPSHOTS MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE DEV_TABCOL_RELEASE_SNAPSHOTS ADD CONSTRAINT DEV_TBRLS2_PK PRIMARY KEY (RELEASE_LABEL, TABLE_NAME, COLUMN_NAME)
  USING INDEX  ENABLE
/


--rollback drop table DEV_TABCOL_RELEASE_SNAPSHOTS;
