--liquibase formatted sql
--changeset table_script:DEV_TABLE_ABBREVIATIONS stripComments:false 
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where upper(table_name) = upper('DEV_TABLE_ABBREVIATIONS');
--------------------------------------------------------------------------------
--
--      Author:  hayden.h.hudson@oracle.com
-- Script name:  DEV_TABLE_ABBREVIATIONS.sql
--        Date:  07-Apr-2023 16:04
--     Purpose:  Table creation DDL for table DEV_TABLE_ABBREVIATIONS
--               and related objects.
--
--------------------------------------------------------------------------------


  CREATE TABLE DEV_TABLE_ABBREVIATIONS 
   (	SCHEMA_NAME VARCHAR2(60 CHAR), 
	TABLE_NAME VARCHAR2(60 CHAR), 
	TABLE_DOMAIN VARCHAR2(5 CHAR), 
	TABLE_ALIAS VARCHAR2(6 CHAR), 
	TABLE_ABBREVIATION VARCHAR2(30 CHAR), 
	COMMENTS VARCHAR2(500 CHAR), 
	PRODUCTION_TABLE VARCHAR2(1 CHAR) DEFAULT ON NULL 'Y', 
	INC_CSSAP_COMPLIANCE VARCHAR2(1 CHAR), 
	SYSTEM_CONFIG_TABLE VARCHAR2(1 CHAR) DEFAULT ON NULL 'N', 
	REVIEW_STATUS VARCHAR2(1 CHAR) DEFAULT ON NULL 'R', 
	CREATED_ON TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp, 
	CREATED_BY VARCHAR2(255) DEFAULT ON NULL user, 
	UPDATED_ON TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	QA_FEEDBACK VARCHAR2(4000)
   ) 
/

  CREATE UNIQUE INDEX DEV_TABBRV_IDX1 ON DEV_TABLE_ABBREVIATIONS (TABLE_DOMAIN, TABLE_ALIAS) 
  
/




  ALTER TABLE DEV_TABLE_ABBREVIATIONS MODIFY (SCHEMA_NAME NOT NULL ENABLE)
/


  ALTER TABLE DEV_TABLE_ABBREVIATIONS MODIFY (TABLE_NAME NOT NULL ENABLE)
/

  ALTER TABLE DEV_TABLE_ABBREVIATIONS MODIFY (SYSTEM_CONFIG_TABLE NOT NULL ENABLE)
/


  ALTER TABLE DEV_TABLE_ABBREVIATIONS MODIFY (REVIEW_STATUS NOT NULL ENABLE)
/


  ALTER TABLE DEV_TABLE_ABBREVIATIONS MODIFY (CREATED_ON NOT NULL ENABLE)
/


  ALTER TABLE DEV_TABLE_ABBREVIATIONS MODIFY (CREATED_BY NOT NULL ENABLE)
/


  ALTER TABLE DEV_TABLE_ABBREVIATIONS ADD CONSTRAINT DEV_TABBRV_CK2 CHECK ( inc_cssap_compliance IN ( 'N', 'Y' ) ) ENABLE
/


  ALTER TABLE DEV_TABLE_ABBREVIATIONS ADD CONSTRAINT DEV_TBLBBR_CK1 CHECK ( review_status IN ( 'A', 'R' ) ) ENABLE
/


  ALTER TABLE DEV_TABLE_ABBREVIATIONS ADD CONSTRAINT DEV_TBLBBR_PK PRIMARY KEY (SCHEMA_NAME, TABLE_NAME)
  USING INDEX  ENABLE
/


  ALTER TABLE DEV_TABLE_ABBREVIATIONS ADD CONSTRAINT DEV_TBLBBR_UN1 UNIQUE (TABLE_DOMAIN, TABLE_ALIAS)
  USING INDEX DEV_TABBRV_IDX1  ENABLE
/


--rollback drop table DEV_TABLE_ABBREVIATIONS;
